# Dockerfile.namenode
FROM adoptopenjdk:8

# Define a variável de ambiente JAVA_HOME
ENV JAVA_HOME /path/to/jdk-22

# Outras instruções do Dockerfile...


# Use the base Hadoop namenode image
FROM docker.io/bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8

# Create the hadoop group
RUN groupadd hadoop

# Add the hdfs user to the hadoop group and create the home directory
RUN useradd --create-home --shell /bin/bash --groups hadoop hdfs
